export const dummy_data = [
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
    'Wah Tee',
    'KFC',
    'Sate Kyite Hotpot',
]
